name: Android CI

on:
  pull_request:
    branches:
    - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Copy google-services.json
      run: base64 --decode ${{ secrets.GOOGLE_SERVICES_JSON }} > app/google-services.json
    - name: Execute gradle
      run: bash ./gradlew clean assembleDebug









